package wrapper

// A Plugin provides functionalities for code generation.
type Plugin interface {
	// Name identifies the plugin
	Name() string

	// Init is called once after data structures are built but before
	// code generation begins.
	Init(g *Generator) error

	// Generate produces the code generated by the plugin for this file,
	// by calling the generator's methods P, In, and Out.
	Generate(file *FileDescriptor) error
}

// EOF
